### ISSUE TITLE
isqrt is slow

### ISSUE THREAD

**Issue by wjmelements** [lapets/isqrt#1]
It is faster for scipy to compute lambertw than for this to compute isqrt.

You should [bind to C](https://realpython.com/python-bindings-overview/#ctypes) and do it there. Supporting python's big int looks like the main difficulty of porting the code.

**Comment by wjmelements** [comment]
I recommend anyone looking for performance to prefer `gmpy2.isqrt`

**Comment by mdickinson** [comment]
> I recommend anyone looking for performance to prefer `gmpy2.isqrt`

@wjmelements There's also `math.isqrt`, since Python 3.8.
