### ISSUE TITLE
linear running time performance claim is inaccurate

### ISSUE THREAD

**Issue by mdickinson** [lapets/isqrt#2]
A minor documentation bug: the claim in the README that 

> The running time is linear in the bit length of the input integer

is not quite correct. The operation count (that is, counting Python-level operations) is certainly linear, but some of those operations themselves have linear running time - the most obvious being the subtraction in the line [`rmdr -= cand * bit_next`](https://github.com/lapets/isqrt/blob/f987cd163c863237a5ab77911ba43569ac1bcc6d/isqrt/isqrt.py#L60). Maybe the statement could be corrected to something like "The number of operations is linear in the bit length of the input integer."?

**Comment by lapets** [comment]
Thanks, that's a good point! README fixed as of 95d03c0f92ec4bc266e423506cde877470558ab5.

In case you have ideas, the introduction of [math.isqrt](https://docs.python.org/3/library/math.html#math.isqrt) suggests it may be time to put the package name to better use (*e.g.*, as a wrapper for specialized/optimized variants such as [yours](https://gist.github.com/mdickinson/e087001d213725a93eeb8d8f447a2f40) for specific conditions, or perhaps a version with a modulus parameter in the style of [pow](https://docs.python.org/3/library/functions.html#pow)).
